"""create initial tables

Revision ID: dff46c684cc4
Revises: 
Create Date: 2026-04-29 11:52:46.185370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dff46c684cc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=False),
    sa.Column('longitude', sa.Numeric(), nullable=False),
    sa.Column('geo', sa.Text(), nullable=True),
    sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rating', sa.Numeric(), nullable=True),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_location_type'), 'locations', ['location_type'], unique=False)
    op.create_table('partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('partner_type', sa.String(length=50), nullable=False),
    sa.Column('priority_level', sa.Integer(), nullable=True),
    sa.Column('commission_model', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('charging_stations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('connector_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_power_kw', sa.Numeric(), nullable=True),
    sa.Column('price_per_kwh', sa.Numeric(), nullable=True),
    sa.Column('availability_status', sa.String(length=50), nullable=False),
    sa.Column('reliability_score', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charging_stations_location_id'), 'charging_stations', ['location_id'], unique=True)
    op.create_table('driver_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_name', sa.String(length=100), nullable=True),
    sa.Column('profile_type', sa.String(length=50), nullable=False),
    sa.Column('preferred_amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_brands', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avoid_tolls', sa.Boolean(), nullable=False),
    sa.Column('avoid_highways', sa.Boolean(), nullable=False),
    sa.Column('max_detour_minutes', sa.Integer(), nullable=True),
    sa.Column('break_frequency_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_profiles_user_id'), 'driver_profiles', ['user_id'], unique=False)
    op.create_table('fuel_stations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('fuel_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_per_liter', sa.Numeric(), nullable=True),
    sa.Column('availability_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_stations_location_id'), 'fuel_stations', ['location_id'], unique=True)
    op.create_table('loyalty_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('points_balance', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_accounts_user_id'), 'loyalty_accounts', ['user_id'], unique=True)
    op.create_table('partner_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', 'location_id', name='uq_partner_location')
    )
    op.create_index(op.f('ix_partner_locations_location_id'), 'partner_locations', ['location_id'], unique=False)
    op.create_index(op.f('ix_partner_locations_partner_id'), 'partner_locations', ['partner_id'], unique=False)
    op.create_table('service_centers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('supported_brands', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('service_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_authorized', sa.Boolean(), nullable=False),
    sa.Column('booking_url', sa.Text(), nullable=True),
    sa.Column('availability_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_centers_location_id'), 'service_centers', ['location_id'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('powertrain', sa.String(length=30), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=True),
    sa.Column('battery_capacity_kwh', sa.Numeric(), nullable=True),
    sa.Column('fuel_tank_liters', sa.Numeric(), nullable=True),
    sa.Column('consumption_kwh_per_100km', sa.Numeric(), nullable=True),
    sa.Column('consumption_l_per_100km', sa.Numeric(), nullable=True),
    sa.Column('service_interval_km', sa.Integer(), nullable=True),
    sa.Column('service_interval_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin')
    )
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)
    op.create_table('partner_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('partner_location_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('offer_type', sa.String(length=50), nullable=False),
    sa.Column('discount_percent', sa.Numeric(), nullable=True),
    sa.Column('fixed_discount_amount', sa.Numeric(), nullable=True),
    sa.Column('loyalty_points', sa.Integer(), nullable=True),
    sa.Column('commission_value', sa.Numeric(), nullable=True),
    sa.Column('campaign_priority', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['partner_location_id'], ['partner_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_offers_partner_id'), 'partner_offers', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partner_offers_partner_location_id'), 'partner_offers', ['partner_location_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_profile_id', sa.UUID(), nullable=True),
    sa.Column('origin_label', sa.String(length=255), nullable=True),
    sa.Column('origin_lat', sa.Numeric(), nullable=True),
    sa.Column('origin_lng', sa.Numeric(), nullable=True),
    sa.Column('destination_label', sa.String(length=255), nullable=True),
    sa.Column('destination_lat', sa.Numeric(), nullable=True),
    sa.Column('destination_lng', sa.Numeric(), nullable=True),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_mode', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_profile_id'], ['driver_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_driver_profile_id'), 'trips', ['driver_profile_id'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_index(op.f('ix_trips_vehicle_id'), 'trips', ['vehicle_id'], unique=False)
    op.create_table('vehicle_state_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('battery_soc_percent', sa.Numeric(), nullable=True),
    sa.Column('fuel_level_percent', sa.Numeric(), nullable=True),
    sa.Column('estimated_range_km', sa.Numeric(), nullable=True),
    sa.Column('odometer_km', sa.Numeric(), nullable=True),
    sa.Column('tire_pressure_status', sa.String(length=50), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_state_snapshots_vehicle_id'), 'vehicle_state_snapshots', ['vehicle_id'], unique=False)
    op.create_table('assistant_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('input_type', sa.String(length=30), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('extracted_intent', sa.String(length=100), nullable=True),
    sa.Column('extracted_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_requests_trip_id'), 'assistant_requests', ['trip_id'], unique=False)
    op.create_index(op.f('ix_assistant_requests_user_id'), 'assistant_requests', ['user_id'], unique=False)
    op.create_table('route_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('route_name', sa.String(length=255), nullable=True),
    sa.Column('polyline', sa.Text(), nullable=True),
    sa.Column('distance_km', sa.Numeric(), nullable=True),
    sa.Column('duration_minutes', sa.Numeric(), nullable=True),
    sa.Column('traffic_duration_minutes', sa.Numeric(), nullable=True),
    sa.Column('estimated_energy_kwh', sa.Numeric(), nullable=True),
    sa.Column('estimated_fuel_liters', sa.Numeric(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(), nullable=True),
    sa.Column('toll_cost', sa.Numeric(), nullable=True),
    sa.Column('route_score', sa.Numeric(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('scoring_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_options_trip_id'), 'route_options', ['trip_id'], unique=False)
    op.create_table('service_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=True),
    sa.Column('urgency', sa.String(length=30), nullable=False),
    sa.Column('odometer_km', sa.Numeric(), nullable=True),
    sa.Column('km_until_service', sa.Numeric(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('recommended_service_center_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recommended_service_center_id'], ['service_centers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_alerts_recommended_service_center_id'), 'service_alerts', ['recommended_service_center_id'], unique=False)
    op.create_index(op.f('ix_service_alerts_trip_id'), 'service_alerts', ['trip_id'], unique=False)
    op.create_index(op.f('ix_service_alerts_vehicle_id'), 'service_alerts', ['vehicle_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('assistant_request_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('selected_route_option_id', sa.UUID(), nullable=True),
    sa.Column('final_score', sa.Numeric(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('scoring_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assistant_request_id'], ['assistant_requests.id'], ),
    sa.ForeignKeyConstraint(['selected_route_option_id'], ['route_options.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_assistant_request_id'), 'recommendations', ['assistant_request_id'], unique=False)
    op.create_index(op.f('ix_recommendations_selected_route_option_id'), 'recommendations', ['selected_route_option_id'], unique=False)
    op.create_index(op.f('ix_recommendations_trip_id'), 'recommendations', ['trip_id'], unique=False)
    op.create_table('route_stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_option_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('stop_type', sa.String(length=50), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('detour_minutes', sa.Numeric(), nullable=True),
    sa.Column('detour_distance_km', sa.Numeric(), nullable=True),
    sa.Column('planned_arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_duration_minutes', sa.Numeric(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['route_option_id'], ['route_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_stops_location_id'), 'route_stops', ['location_id'], unique=False)
    op.create_index(op.f('ix_route_stops_route_option_id'), 'route_stops', ['route_option_id'], unique=False)
    op.create_table('recommendation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('route_option_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('partner_offer_id', sa.UUID(), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('driver_value_score', sa.Numeric(), nullable=True),
    sa.Column('partner_boost_score', sa.Numeric(), nullable=True),
    sa.Column('loyalty_score', sa.Numeric(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['partner_offer_id'], ['partner_offers.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['route_option_id'], ['route_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_items_location_id'), 'recommendation_items', ['location_id'], unique=False)
    op.create_index(op.f('ix_recommendation_items_partner_offer_id'), 'recommendation_items', ['partner_offer_id'], unique=False)
    op.create_index(op.f('ix_recommendation_items_recommendation_id'), 'recommendation_items', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_items_route_option_id'), 'recommendation_items', ['route_option_id'], unique=False)
    op.create_table('loyalty_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loyalty_account_id', sa.UUID(), nullable=False),
    sa.Column('partner_offer_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_item_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loyalty_account_id'], ['loyalty_accounts.id'], ),
    sa.ForeignKeyConstraint(['partner_offer_id'], ['partner_offers.id'], ),
    sa.ForeignKeyConstraint(['recommendation_item_id'], ['recommendation_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_transactions_loyalty_account_id'), 'loyalty_transactions', ['loyalty_account_id'], unique=False)
    op.create_index(op.f('ix_loyalty_transactions_partner_offer_id'), 'loyalty_transactions', ['partner_offer_id'], unique=False)
    op.create_index(op.f('ix_loyalty_transactions_recommendation_item_id'), 'loyalty_transactions', ['recommendation_item_id'], unique=False)
    op.create_table('recommendation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_item_id', sa.UUID(), nullable=True),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['recommendation_item_id'], ['recommendation_items.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_events_event_type'), 'recommendation_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_recommendation_events_partner_id'), 'recommendation_events', ['partner_id'], unique=False)
    op.create_index(op.f('ix_recommendation_events_recommendation_id'), 'recommendation_events', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_events_recommendation_item_id'), 'recommendation_events', ['recommendation_item_id'], unique=False)
    op.create_index(op.f('ix_recommendation_events_trip_id'), 'recommendation_events', ['trip_id'], unique=False)
    op.create_index(op.f('ix_recommendation_events_user_id'), 'recommendation_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_events_user_id'), table_name='recommendation_events')
    op.drop_index(op.f('ix_recommendation_events_trip_id'), table_name='recommendation_events')
    op.drop_index(op.f('ix_recommendation_events_recommendation_item_id'), table_name='recommendation_events')
    op.drop_index(op.f('ix_recommendation_events_recommendation_id'), table_name='recommendation_events')
    op.drop_index(op.f('ix_recommendation_events_partner_id'), table_name='recommendation_events')
    op.drop_index(op.f('ix_recommendation_events_event_type'), table_name='recommendation_events')
    op.drop_table('recommendation_events')
    op.drop_index(op.f('ix_loyalty_transactions_recommendation_item_id'), table_name='loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_transactions_partner_offer_id'), table_name='loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_transactions_loyalty_account_id'), table_name='loyalty_transactions')
    op.drop_table('loyalty_transactions')
    op.drop_index(op.f('ix_recommendation_items_route_option_id'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_recommendation_id'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_partner_offer_id'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_location_id'), table_name='recommendation_items')
    op.drop_table('recommendation_items')
    op.drop_index(op.f('ix_route_stops_route_option_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_location_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_recommendations_trip_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_selected_route_option_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_assistant_request_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_service_alerts_vehicle_id'), table_name='service_alerts')
    op.drop_index(op.f('ix_service_alerts_trip_id'), table_name='service_alerts')
    op.drop_index(op.f('ix_service_alerts_recommended_service_center_id'), table_name='service_alerts')
    op.drop_table('service_alerts')
    op.drop_index(op.f('ix_route_options_trip_id'), table_name='route_options')
    op.drop_table('route_options')
    op.drop_index(op.f('ix_assistant_requests_user_id'), table_name='assistant_requests')
    op.drop_index(op.f('ix_assistant_requests_trip_id'), table_name='assistant_requests')
    op.drop_table('assistant_requests')
    op.drop_index(op.f('ix_vehicle_state_snapshots_vehicle_id'), table_name='vehicle_state_snapshots')
    op.drop_table('vehicle_state_snapshots')
    op.drop_index(op.f('ix_trips_vehicle_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver_profile_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_partner_offers_partner_location_id'), table_name='partner_offers')
    op.drop_index(op.f('ix_partner_offers_partner_id'), table_name='partner_offers')
    op.drop_table('partner_offers')
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_service_centers_location_id'), table_name='service_centers')
    op.drop_table('service_centers')
    op.drop_index(op.f('ix_partner_locations_partner_id'), table_name='partner_locations')
    op.drop_index(op.f('ix_partner_locations_location_id'), table_name='partner_locations')
    op.drop_table('partner_locations')
    op.drop_index(op.f('ix_loyalty_accounts_user_id'), table_name='loyalty_accounts')
    op.drop_table('loyalty_accounts')
    op.drop_index(op.f('ix_fuel_stations_location_id'), table_name='fuel_stations')
    op.drop_table('fuel_stations')
    op.drop_index(op.f('ix_driver_profiles_user_id'), table_name='driver_profiles')
    op.drop_table('driver_profiles')
    op.drop_index(op.f('ix_charging_stations_location_id'), table_name='charging_stations')
    op.drop_table('charging_stations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('partners')
    op.drop_index(op.f('ix_locations_location_type'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
